server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/departments/**
        - id: salary-service
          uri: lb://salary-service
          predicates:
            - Path=/api/salaries/**
        - id: absence-service
          uri: lb://absence-service
          predicates:
            - Path=/api/leaves/**
        - id: training-service
          uri: lb://training-service
          predicates:
            - Path=/api/trainings/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/